---
galaxy_info:
  role_name: php-mysql_install
  author: JeroenHaverkort
  description: Ansible role that installs php-mysql (php-mysqlnd) on AlmaLinux using dnf.
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: AlmaLinux
      versions:
        - 8
        - 9
dependencies: []
